version: "2"
services:
  dawei:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - VIRTUAL_HOST=dawei.io,www.dawei.io
      - LETSENCRYPT_HOST=dawei.io,www.dawei.io
      - VIRTUAL_PORT=80

networks:
  default:
    external:
      name: nginx-proxy
